name: pengaduan_desa
description: Aplikasi Pengaduan Desa
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  file_picker: ^10.3.7
  image_picker: ^1.0.7
  intl: ^0.18.1
  fluttertoast: ^8.2.4 
  path_provider: ^2.1.3
  permission_handler: ^11.0.2
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png